# Node 20.15.0
FROM node:slim

WORKDIR /shindow/frontend-shindow

COPY package.json .

RUN npm install

COPY .next ./.next
COPY public ./public
COPY entrypoint.sh ./entrypoint.sh

RUN chmod +x ./entrypoint.sh

EXPOSE 3000

ENTRYPOINT ["./entrypoint.sh"]
CMD ["npm", "start"]